spring:
  application:
    name: inventory
  # email 전송 테스트용
  mail:
    host: localhost
    port: 1025

  config:
    import: optional:file:.env[.properties]

  # 데이터베이스 연결 설정
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 콘솔 사용 (웹에서 데이터베이스 보기)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # Redis Connection Configuration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}

server:
  port: ${SERVER_PORT:10411}

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry
  endpoint:
    health:
      show-details: never

# medicine API
medicine:
  api:
    base-url: https://apis.data.go.kr/1471000/DrugPrdtPrmsnInfoService07
    detail-path: /getDrugPrdtPrmsnDtlInq06
    service-key: d9149176405bff9304536370ec6a5d7278891b544707a426bfb79fac8f87e586

# 초대 base url
app:
  invitation-url: https://iunot.cloud/signup
