eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

clients:
  account:
    base-url: ${ACCOUNT_BASE_URL:http://account}
  rule-engine:
    base-url: ${RULE_ENGINE_BASE_URL:http://rule-engine}

logging:
  level:
    com.nhnacademy.inventory: INFO
    org.springframework: WARN

management:
  tracing:
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT}

# 초대 base url
app:
  invitation-url: https://iunot.cloud/signup

security:
  jwt:
    jwk-set-uri: http://team1-account-1:10413/.well-known/jwks.json
