eureka:
  client:
    enabled: false

clients:
  account:
    base-url: ${ACCOUNT_BASE_URL:http://localhost:10413}
  rule-engine:
    base-url: ${RULE_ENGINE_BASE_URL:http://localhost:10406}

management:
  tracing:
    export:
      zipkin:
        enabled: false

# 초대 base url
app:
  invitation-url: localhost:10404/signup

security:
  jwt:
    jwk-set-uri: http://localhost:10413/api/auth/.well-known/jwks.json

