spring:
  flyway:
    # 기존 운영 DB 스키마를 버전 1로 간주하고, 그 이후 변경 사항만 마이그레이션 스크립트로 관리
    baseline-on-migrate: true
    baseline-version: 1

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  level:
    com.nhnacademy.inventory: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry, prometheus
  tracing:
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT}

# 초대 base url
app:
  invitation-url: https://iunot.cloud/signup

security:
  jwt:
    jwk-set-uri: https://iunot.cloud/.well-known/jwks.json

