eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

logging:
  level:
    com.nhnacademy.inventory: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, service-registry, prometheus
  tracing:
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT}

# 초대 base url
app:
  invitation-url: https://iunot.cloud/signup

security:
  jwt:
    jwk-set-uri: https://iunot.cloud/.well-known/jwks.json

